# Generated by Django 4.1.7 on 2023-03-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reporting.business'),
        ),
        migrations.AddField(
            model_name='job',
            name='lineitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='reporting.lineitem'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_items', to='reporting.job'),
        ),
    ]
