# Generated by Django 4.1.7 on 2023-03-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_job_business_job_lineitems_alter_lineitem_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='self_item',
        ),
    ]
