# Generated by Django 4.1.7 on 2023-03-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_lineitem_self_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='lineitems',
        ),
    ]
