# Generated by Django 4.1.7 on 2023-03-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_remove_job_lineitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='reporting.business'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='reporting.customer'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_items', to='reporting.invoice'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='line_items', to='reporting.payment'),
        ),
    ]
